(SAM-5) Добавила модель данных
FocusStartSpb/PhotoTune pull request #11
Opened 2019-12-17 20:14 UTC by anna-belousova

свойство name пока оставила

2019-12-17 20:31 UTC, c0dedbear commented on PhotoTune.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 2VAU5M9JPP;
Это не нужно коммиттить.

2019-12-17 20:31 UTC, c0dedbear commented on PhotoTune.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = "Anna-Belousova.PhotoTune";
Это не нужно коммитить.

2019-12-17 20:44 UTC, c0dedbear requested changes
1. Убрать из коммитов изменение настроек проекта( bundle id, team).
2. Убрать лишний код (инит) из структуры.
3. Дать более определённое имя структуре.

2019-12-17 20:44 UTC, c0dedbear commented on PhotoTune/BusinessLayer/ImageModel.swift
> +	}
Структурам, в отличии от классов не нужно явно прописывать иницилизатор если тебе не нужно их как то по особому инициализировать. 

Свойство name давай уберем или сделаем опционалом. (юзер может не захотеть давать имя)

2019-12-17 20:44 UTC, c0dedbear commented on PhotoTune/Modules/ViewController.swift
> +{
О, возможно у нас будет конфликт при мердже, так как я изменил это в своем пулреквесте. Сейчас становится понятно, что лучше не трогать, то что напрямую не связано с задачей.

2019-12-17 20:44 UTC, c0dedbear commented on PhotoTune/BusinessLayer/ImageModel.swift
> +struct ImageModel
Думаю что слово Model можно убрать так как это само собой вытекает из назначения и расположения файла в проекте, но назвать модель более определенно, например EditedImage. Ведь это именно отредактированный Image, а не например тот что приходит по сети.

2019-12-17 20:54 UTC, c0dedbear requested changes

2019-12-17 20:54 UTC, c0dedbear commented on PhotoTune/BusinessLayer/ImageModel.swift
> +import UIKit
Думаю, что не очень хорошая идея импортить UIKit в бизнес логику и хранить непосредственно сам UImage в модели, вместо этого можно хранить String с путем где лежит image или именем в случае заглушки.

2019-12-18 14:48 UTC, MisnikovRoman commented on PhotoTune/Modules/ViewController.swift
> +{
@c0dedbear ты прозрел 👀

2019-12-18 17:33 UTC, anna-belousova commented on PhotoTune/BusinessLayer/ImageModel.swift
> +	}
fixed

2019-12-18 17:33 UTC, anna-belousova commented on PhotoTune/BusinessLayer/ImageModel.swift
> +struct ImageModel
fixed

2019-12-18 17:33 UTC, anna-belousova commented on PhotoTune/BusinessLayer/ImageModel.swift
> +import UIKit
fixed

2019-12-19 11:09 UTC, c0dedbear submitted a review, later dismissed

2019-12-19 11:45 UTC, svshkv submitted a review, later dismissed

2019-12-19 11:55 UTC, c0dedbear approved these changes

2019-12-19 12:20 UTC, svshkv approved these changes

2019-12-19 12:21 UTC, merged