(SAM-11) Cоздал лэйаут и ячейку коллекшн вью
FocusStartSpb/PhotoTune pull request #24
Opened 2019-12-21 10:51 UTC by svshkv

2019-12-21 10:52 UTC, c0dedbear submitted a review, later dismissed

2019-12-21 15:17 UTC, anna-belousova approved these changes

2019-12-21 23:06 UTC, anna-belousova requested changes

2019-12-21 23:06 UTC, anna-belousova commented on PhotoTune/BusinessLayer/CollectionViewSettings/CollectionViewCell.swift
> +{
Я хочу наследоваться от ImageCollectionViewCell, для этого нужно убрать final

2019-12-22 10:37 UTC, c0dedbear requested changes
Влить последния изменения develop ветки (имеется конфликт)

2020-01-10 09:27 UTC, closed without merging